name: CI

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      build_linux_amdgpu_families:
        type: string
        description: "Insert comma-separated list of Linux GPU families to build. ex: gfx94X, gfx1201X"
        default: ""
      build_windows_amdgpu_families:
        type: string
        description: "Insert comma-separated list of Windows GPU families to build. ex: gfx94X, gfx1201X"
        default: ""
      test_linux_amdgpu_families:
        type: string
        description: "Insert comma-separated list of Linux GPU families to test. ex: gfx94X, gfx1201X"
        default: ""
      test_windows_amdgpu_families:
        type: string
        description: "Insert comma-separated list of Windows GPU families to test. ex: gfx94X, gfx1201X"
        default: ""
      artifact_run_id:
        type: string
        description: "If provided, the tests will run on this artifact ID"
        default: ""
  # By default, We have selected build/test linux and windows targets in configure_ci.py.
  # In order to run build and tests, please select a provided label corresponding with the machine and OS (ex: gfx94X-linux)
  # If the label is already added, you can remove and re-add the label to restart the job.
  # TODO (geo): improve pull request experience, whether with labels or comments
  pull_request:
    types:
      - pushed
      - labeled
      - opened

permissions:
  contents: read

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit). The workflow name is prepended to avoid conflicts between
  # different workflows.
  group: ${{ github.workflow }}-${{ github.event.number || github.sha }}
  cancel-in-progress: true

jobs:
  add_default_targets_for_pr:
    name: "Add default targets for pull request"
    if: ${{ github.event.action == 'opened' }} # run if this is a PR and PR was opened
    runs-on: ubuntu-24.04
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PR_NUMBER: ${{ github.event.number }}
    steps:
      - name: "Adding labels"
        run: |
          gh pr edit ${PR_NUMBER} --add-label "gfx94X-linux"
          gh pr edit ${PR_NUMBER} --add-label "gfx110X-linux"
          gh pr edit ${PR_NUMBER} --add-label "gfx110X-windows"

  setup:
    uses: ./.github/workflows/setup.yml

  build_linux_packages:
    name: Build Linux Packages
    needs: setup
    if: ${{ needs.setup.outputs.build_linux_amdgpu_families != '[]' }}
    strategy:
      matrix:
        families: ${{ fromJSON(needs.setup.outputs.build_linux_amdgpu_families) }}
    uses: ./.github/workflows/build_linux_packages.yml
    with:
      amdgpu_families: ${{ matrix.families.target }}
    permissions:
      id-token: write

  build_windows_packages:
    name: Build Windows Packages
    needs: setup
    if: ${{ needs.setup.outputs.build_windows_amdgpu_families != '[]' }}
    strategy:
      matrix:
        families: ${{ fromJSON(needs.setup.outputs.build_windows_amdgpu_families) }}
    uses: ./.github/workflows/build_windows_packages.yml
    with:
      amdgpu_families: ${{ matrix.families.target }}

  test_linux_packages:
    needs: [setup, build_linux_packages]
    name: Test Linux Packages
    if: |
      ${{
        !cancelled() &&
        needs.setup.outputs.test_linux_amdgpu_families != '[]' &&
        (
          needs.build_linux_packages.result == 'success' ||
          needs.build_linux_packages.result == 'skipped'
        )
      }}
    strategy:
      matrix:
        families: ${{ fromJSON(needs.setup.outputs.test_linux_amdgpu_families) }}
    uses: ./.github/workflows/test_linux_packages.yml
    with:
      amdgpu_families: ${{ matrix.families.target }}
      test_runs_on: ${{ matrix.families.test-runs-on }}
      artifact_run_id: ${{ inputs.artifact_run_id }}

  # build_python_packages:
  #   name: Build Python Packages
  #   uses: ./.github/workflows/build_python_packages.yml
