name: Test Linux Packages

on:
  workflow_dispatch:
    inputs:
      artifact_run_id:
        type: string
        default: ""
      amdgpu_families:
        type: string
      test_runs_on:
        type: string
  workflow_call:
    inputs:
      artifact_run_id:
        type: string
        default: ""
      amdgpu_families:
        type: string
      test_runs_on:
        type: string
  push:
    branches:
      - ADHOCBUILD

jobs:
  test_sanity_check:
    name: 'Test Sanity Check'
    if: ${{ inputs.test_runs_on != "" }} # if there is a test machine available
    uses: './.github/workflows/test_sanity_check.yml'
    with:
      artifact_run_id: ${{ inputs.artifact_run_id }}
      test_runs_on: ${{ inputs.test_runs_on }}

  test_blas:
    name: 'Test BLAS math-lib'
    if: ${{ inputs.test_runs_on != "" }} # if there is a test machine available
    uses: './.github/workflows/test_blas.yml'
    needs: test_sanity_check
    with:
      artifact_run_id: ${{ inputs.artifact_run_id }}
      amdgpu_families: ${{ inputs.amdgpu_families }}
      test_runs_on: ${{ inputs.test_runs_on }}
